modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="betons_rations_and_food"
version="1.0.0"
displayName="Beton's Rations and food mod"
displayURL="https://modrinth.com/user/ConcreteGuy"
credits="Everyone"
authors="Beton"
description="I can't play with Pam's harvest craft 2 on 1.19.4, so i made this mod"

[[dependencies.betons_rations_and_food]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




